### PR TITLE
docs: update some outdated links

### PR DESCRIPTION
**Pull request by JounQin**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

As title

### CODE REVIEW

**Comment by JounQin** [comment]
cc @remcohaszing 

No idea why the CI is failing.

**Review by ChristianMurphy — APPROVED** [review]

**Comment by remcohaszing** [comment]
Thanks! I wonder if we shouldn’t remove or at least trim down this section though. It feels like the wrong place to document how to use ESLint with MDX, except for the `eslint.validate` setting.

**Comment by remcohaszing** [comment]
Don’t worry about the CI failure. That’s my fault, not related to this PR.

**Comment by remcohaszing** [comment]
I will merge this as-is, because updating the links is a good change on its own.

**Comment by JounQin** [comment]
> Thanks! I wonder if we shouldn’t remove or at least trim down this section though. It feels like the wrong place to document how to use ESLint with MDX, except for the `eslint.validate` setting.

I believe that is a good place to document such related tools together in one place considering it's short enough. It would be easier to be found for users.

**Pull request merged**
